### ISSUE TITLE
[Request Update] Minecraft Bedrock v1.20.70/71

### ISSUE THREAD

**Issue by TheWeaknd** [laynebritton/jl-fast-treecapitator#42]
So Minecraft release new version, please update the addon. Thank you so much.

**Comment by laynebritton** [comment]
Hi @TheWeaknd ,

Thank you for flagging this issue to us.

I am currently unable to download version `v1.20.70/71` of Minecraft Bedrock, due to Microsoft preventing Windows users from accessing the update due to a bug.
See https://bugs.mojang.com/browse/MCPE-179688

> The update is currently paused on Windows to prevent world loss issues (tracking in [MCPE-174716](https://bugs.mojang.com/browse/MCPE-174716). For players who didn't receive the update, some online services may be unavailable, including cross-platform multiplayer.

I am unable to set up version 1.20.70/71 for development until this is resolved. After Microsoft fixes this, we will be able to resolve the breaking changes caused by changes to modding api in `v1.20.70/71`

Layne
